### PR TITLE
feat: expose LicenseUrl in output

### PR DESCRIPTION
**Pull request by garcipat**
License Url is part of the license information domain model and is very helpful to get the license content. as mentioned in #32
I would like to expose this.

### CODE REVIEW

**Comment by garcipat** [comment]
I would also like to expose the repository since some license information are not correct in packages and this allows to fix those issues. But you mentioned you don't want to expose that field.

**Comment by sensslen** [comment]
Hi @garcipat, thank you for your contribution. I do have a few notes on the proposed changes:
- Can you please add UnitTests for the feature you implemented?
- The problem with using the repository to grab the license is that the license could have been changed. I'd strongly recommend to manually resolve such issues by using the built in overwrite capabilities --> See https://github.com/sensslen/nuget-license/blob/main/.github/workflows/assets/Tests/overwritePackageInformation.json and https://github.com/sensslen/nuget-license/blob/main/.github/workflows/assets/Tests/ignorePackages.json
- Can you please add the license url to the tabular output?

**Review by sensslen — CHANGES_REQUESTED** [review]
Hi @garcipat, thank you for your contribution. I do have a few notes on the proposed changes:

- Can you please add UnitTests for the feature you implemented?
- The problem with using the repository to grab the license is that the license could have been changed. I'd strongly recommend to manually resolve such issues by using the built in overwrite capabilities --> See https://github.com/sensslen/nuget-license/blob/main/.github/workflows/assets/Tests/overwritePackageInformation.json and https://github.com/sensslen/nuget-license/blob/main/.github/workflows/assets/Tests/ignorePackages.json
- Can you please add the license url to the tabular output?

**Comment by garcipat** [comment]
I'm currently struggling with the snapshots in the tests since the json is just one line and not human readable at all. I wonder if we could make it formatted instead of a one line json.

**Comment by sensslen** [comment]
Well the snapshots exist for three different variants. tabular, human readable json and compressed json. Verify will generate a new file when the content does not match. You can copy that content over and check whether the changes make sense

**Comment by garcipat** [comment]
> Well the snapshots exist for three different variants. tabular, human readable json and compressed json. Verify will generate a new file when the content does not match. You can copy that content over and check whether the changes make sense

yes i saw that now. I will verify thw two i can read and update the ones that are just one line and expect them to be ok as well. The snapshots in general change a lot due tu the new added property and that bogus now shifts its generation by one. Maybe at least the error count shuold be fixed at some point, just to make it easier in case of changes of the generation. Buts thats detail. Just noticed that.

**Comment by garcipat** [comment]
@sensslen  The test that is browsing the license Urls is failing. But that has nothing to do with my changes. I can't trigger the Actions again in case it is flaky.

**Review by sensslen — APPROVED** [review]

**Pull request merged**
